language: java
jdk: openjdk13

# matrix:
#   include:
#   - name: "OSX testing"
#     os: osx
#   - name: "Linux testing"
#     os: linux

os:
  - linux
  - osx

env:
  matrix:
    - TARGET: "lab1"
    - TARGET: "lab6"

script:
  - chmod u+x ./travis_scripts/package.sh
  - ./travis_scripts/package.sh
