language: java
jdk: openjdk13

# matrix:
#   include:
#   - name: "OSX testing"
#     os: osx
#   - name: "Linux testing"
#     os: linux

os:
  - linux
  - osx

env:
  matrix:
    - TARGET: "lab1"
    - TARGET: "lab2"

script:
  - cd $TARGET && mvn package
